<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ISolicitudChequeraSoapWSService" targetNamespace="http://impl.solicitudchequera.webservice.ws.nci.profuturo.mx/" xmlns:ns1="http://solicitudchequera.webservice.ws.nci.profuturo.mx/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.solicitudchequera.webservice.ws.nci.profuturo.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="ISolicitudChequeraSoapWSServiceSoapBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:import location="ISolicitudChequeraSoapWSService_i.wsdl" namespace="http://solicitudchequera.webservice.ws.nci.profuturo.mx/">
    </wsdl:import>
  <wsdl:binding name="ISolicitudChequeraSoapWSServiceSoapBinding" type="ns1:ISolicitudChequeraSoapWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizarSolicitudChequera">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="actualizarSolicitudChequera">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="actualizarSolicitudChequeraResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="consultarSaldosPreviosChequera">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="consultarSaldosPreviosChequera">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultarSaldosPreviosChequeraResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="consultarSolicitudChequera">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="consultarSolicitudChequera">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="consultarSolicitudChequeraResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ISolicitudChequeraSoapWSService">
    <wsdl:port binding="tns:ISolicitudChequeraSoapWSServiceSoapBinding" name="ISolicitudChequeraSoapWSPort">
      <soap:address location="http://wasdesaft.profuturo-gnp.net:9080/mit-ben-ws/services/ISolicitudChequeraSoapWSService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>